services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres-url-shortener
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url_shortener
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    command: redis-server --appendonly yes --bind 0.0.0.0
    container_name: redis-url-shortener
    hostname: redis
    volumes:
      - redis-data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"


volumes:
  redis-data:
  postgres-db:
